function ss = getSupportedSystems()
% All supported systems
ss = struct( ...
    'Name',                {'SiemensVida3T', 'GEMagnus3T'}, ...
    'Vendor',              {'Siemens', 'GE' }, ...
    'MaxGrad',             {60/sqrt(3), 60/sqrt(3)}, ...
    'GradUnit',            {'mT/m', 'mT/m'}, ...
    'MaxSlew',             {200/sqrt(3), 200/sqrt(3)}, ...
    'SlewUnit',            {'T/m/s', 'T/m/s'}, ...
    'rfRingdownTime',      {30e-6, 60e-6}, ...
    'rfDeadTime',          {100e-6, 100e-6}, ...
    'adcDeadTime',         {10e-6, 40e-6}, ...
    'adcRasterTime',       {1e-6, 2e-6}, ...
    'blockDurationRaster', {10e-6, 10e-6}, ...
    'B0',                  {3.0, 3.0} ...
    );           
